name: Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up .NET Framework 4.8
        run: |
          choco install netfx-4.8 -y

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Restore NuGet packages
        run: |
          nuget restore MPRISBee.sln

      - name: Build the solution
        run: |
          msbuild MPRISBee.sln /p:Configuration=Release
          
      - name: Upload compiled files
        uses: actions/upload-artifact@v7.0.0
        with:           
          name: mb_MPRISBee
          path: |
            bin/Release/*.dll
            bin/Release/MPRISBee/*.dll
